### ISSUE TITLE
Regex 

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Anlab#132]
https://github.com/ucdavis/Anlab/blob/master/Anlab.Core/Domain/TestItem.cs#L13

I don't think we can filter it like this. There is a test with a code of () in the data we are pulling.
This is probably not a public test, but we have to allow what Labworks allows.

**Comment by srkirkland** [comment]
@jSylvestre We should ask Anlab but I disagree, I don't think that's a valid code so we shouldn't use it.

**Comment by jSylvestre** [comment]
@srkirkland A bunch of their tests start with # (Discounted groups) so that will have to be allowed.

**Comment by srkirkland** [comment]
@jSylvestre this should be associated with #148 I think because you are fixing it in there
