### ISSUE TITLE
Saved Prices

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Anlab#258]
Not sure if this is an issue. But probably is:
1) User creates order, price list is saved
2) Anlab adds a test that isn't in our db
3) Anlab adds the test to our db
4) Anlab "receives" the order. 

But the list of tests with prices when the order was created doe not contain the newly added test item, even though we have added it to the test items...

**Comment by srkirkland** [comment]
@jSylvestre doesn't seem like a big problem to me but it is an interesting side effect of saving test history up-front.
