### ISSUE TITLE
Pull info from ClientId

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Anlab#272]
Then given a ClientID....
       With a WR#  you could look up COPYTO info from 
               TABLE: SUSERFLDS   look at CPYEMAIL   and CPYPHONE

And for client name, email, phone, etc:
     TABLE: USERFLDS
         LOCCODE == ClientID
         cpyemail (default, may change on individual WR#)
         subemail  the Client's email
         subphone, the client's phone

**Comment by jSylvestre** [comment]
SELECT TOP (1000) [LOCCODE]
      ,[CPYEMAIL]
      ,[CPYPHONE]
      ,[SUBEMAIL]
      ,[SUBPHONE]
  FROM [Labworks5].[dbo].[USERFLDS]
  where LOCCODE = 'ZIER1'

**Comment by srkirkland** [comment]
@jSylvestre there has to be like a name somewhere right?

**Comment by jSylvestre** [comment]
First: the default client information associated with that Client ID——
        Table:  LOCLIST
             use LOCCODE (the Client ID) as search key to look up default parameters of the Client ID
                  REPADD1   —  the client name
                  REPADD2   —  where the client works:  eg, SPP, VEG CROPS
                  REPADD3   —  the "copy to" if any with this WR#

  Second: the client info attached to a specific work request——
       Table: SAMPLE
           use LOGBATCH (the WR#)
                  LOCCODE   —  the client ID
                  REPADD1   —  the client name
                  REPADD2   —  where the client works:  eg, SPP, VEG CROPS
                  REPADD3   —  the "copy to" if any with this WR#
