### ISSUE TITLE
Lab Comments/Final Price

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Anlab#294]
The lab comments and final price can be entered Lab/Confirmation/61 and again when the order is finalized.
If it was entered Lab/Confirmation/61 , the info doesn't show up on the finalize screen (But it is persisted in the orderDetails)

**Comment by jSylvestre** [comment]
The lab comments can be easily added, but the adjustment amount may cause problems.
@srkirkland Do you think we should stop passing around the adjustment amount and instead just pass the total amount? From there we can calculate the adjustment amount if we want.

**Comment by srkirkland** [comment]
@jSylvestre Not exactly sure the issue but we should probably be keeping around the total for sure and if that requires recalculating adjustment account on the fly then i think that's ok

**Comment by srkirkland** [comment]
@jSylvestre I think we decided to leave this as-is except that we fix the display values inside the totals boxes (javascript work i think).  That way whatever they added as the adjusted total upon receive stays the adjusted total.

**Comment by laholstege** [comment]
fixed in #310 
adjustment amount is whatever is added on receive + whatever is added on finalize, so grand total is updated appropriately and total itself is the price calculated from the tests
