### ISSUE TITLE
Rush Multiplier

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Anlab#308]
We pull this info to calculate the final price.
Do we want to display this on the order details page?

**Comment by srkirkland** [comment]
@jSylvestre yea if it goes into the final price I think we should add it only if it != 1

**Comment by srkirkland** [comment]
@jSylvestre @laholstege Add rush multiplier to the details pages, anything after receive, once it has a WR#. Will need to start saving in the model

**Comment by jSylvestre** [comment]
FYI, is pulling from the actual/copy of the labworks DB, this is a rush with 1.5 multiplier:
18S063
