### ISSUE TITLE
Invalid KFS account doesn't show error

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Anlab#323]
3-CRU9033SDF is bad, but shows up valid

**Comment by jSylvestre** [comment]
This isn't parsing it correctly
        public AccountModel(string rawAccount)
        {
            var regx = Regex.Match(rawAccount, @"(\w)-(\w{7})\/?(\w{5})?");
            Chart = regx.Groups[1].Value;
            Account = regx.Groups[2].Value;
            SubAccount = regx.Groups[3].Value;
        }
