### ISSUE TITLE
UCD Payment

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Anlab#361]
Finalize State

Move the code that calls sloth and marks the order as paid from the finalize method.
Put it in a "Confirm Payment" method.

The Confirm Payment page should display the current Account Payment Account, and info from the account lookup if available.

They can change to another account and we have to validate that if UCD, but allow if not UCD.
Extra info gathered/changed TBD (Contact name, email, other client info?)

If they change the info instead of just confirming what was there, trigger an email notification?

Mark Paid

**Comment by srkirkland** [comment]
@jSylvestre apparently they just want UCD accounts to get charged immediately when work is done.  Is this how the code is working now or should we double-check and then change?

**Comment by jSylvestre** [comment]
@srkirkland UCD Accounts call sloth when they are finalized.
