### ISSUE TITLE
BUG: Plant material cannot select option 1

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Anlab#407]
Select plant material and then select any non-default option for how you would like your samples reported.  You are not allowed to go back and select the first option ever.  If you do the radio button is just deselected.

Also, if you click the labels they should select the corresponding radio buttons.

**Comment by jSylvestre** [comment]
@srkirkland To make the text selectable, I wrapped in a label . But it makes the text bold. Not sure if you want that:

![image](https://user-images.githubusercontent.com/469010/34834389-c1d23c94-f6a6-11e7-8fb4-f03076747b66.png)
