### ISSUE TITLE
PI's email address should default as one of 'send to' emails

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Anlab#417]
Would require grabbing when we grab the client info.  Should not be editable.

**Comment by jSylvestre** [comment]
We may not want to show the PI's email and/or the submitter's email.

**Comment by srkirkland** [comment]
Agree but i think it's probably just easier to show it anyway

**Comment by srkirkland** [comment]
we aren't currently sending the PI's email to the client when querying clientID

**Comment by jSylvestre** [comment]
I did a little work on this, but I don't really like it.
Some concerns:
1) The data isn't good.
2) copy email and/or sub email?
3) Can the creator remove the emails
4) check for duplicates
5) What if the client id is changed?

**Comment by srkirkland** [comment]
@jSylvestre 

1. well, that sucks
2. not sure, the main email associated w/ a clientID
3. no
4. if the creator and clientID email are the same, sure don't show it 2x
5. we should just have a property for clientEmail that changes w/ clientID.  that's what goes in the list of people to email.

It doesn't even have to be in the email list typer thing if we don't want.  It could just be text.
