### ISSUE TITLE
wording changes on "create form"

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Anlab#418]
See slice 1 from here:

[Website feedback Jan 23 2018.pptx](https://github.com/ucdavis/Anlab/files/1665756/Website.feedback.Jan.23.2018.pptx)

**Comment by jSylvestre** [comment]
1) "Create New Work Request" heading => "Create New Work Order"
2) "Create Order" button => "Create New Order"
3) Credit Card info = > "Your credit card information will be collected at a later date."
4) UC Funds info => "Required to receive the UC Rate."
5) Other info => "Payment by PO or Bank Transfer"
6) "What is the project ..." => What is the project title associated with this order? n/ Project Title / Location is optional and can be user to help organize your submissions.
7) "Commodity" => "Type of Material / Commodity"
8) "Who should be notified... " => "Who should receive emails and results for this sample submission?"
9) "How many samples... " => "How many samples will you be submitting?"
10 "Project Titke" => "Project Title/Location

**Comment by jSylvestre** [comment]
@srkirkland Re  number 6, this is not an optional field.
