### ISSUE TITLE
remove soil imported question?

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Anlab#436]
Soil imported is better left as a test?  Maybe just a comment that they much select the imported soil test if their soil is imported

**Comment by jSylvestre** [comment]
![image](https://user-images.githubusercontent.com/469010/35705041-21b07922-0756-11e8-8094-fb986918312e.png)

**Comment by srkirkland** [comment]
@jSylvestre remove the question entirely, and I'd think about putting the please remember into an info box `<div class="alert alert-info" role="alert">...</div>`
