### ISSUE TITLE
for IOC, ask for campus (or dropdown)

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Anlab#446]

**Comment by jSylvestre** [comment]
[GA_IOC2.xlsx](https://github.com/ucdavis/Anlab/files/1695674/GA_IOC2.xlsx)

**Comment by jSylvestre** [comment]
<div className="form-group">
                        <label>Campus</label>
                        <select className="form-control" id="campus">
                            <option value="">-- Please Select Campus -- </option>
                            <option value="UCB">UC Berkeley</option>
                            <option value="UCSF">UC San Francisco</option>
                            <option value="UCLA">UC Los Angeles</option>
                            <option value="UCR">UC Riverside</option>
                            <option value="UCSD">UC San Diego</option>
                            <option value="UCSC">UC Santa Cruz</option>
                            <option value="UCSB">UC Santa Barbara</option>
                            <option value="UCI">UC Irvine</option>
                            <option value="UCM">UC Merced</option>
                            <option value="M-OP">M-OP</option>
                        </select>
                    </div>

**Comment by jSylvestre** [comment]
When UC account is selected, change company to Campus.
Make S chart accounts non UCD

**Comment by jSylvestre** [comment]
PR #453
