### ISSUE TITLE
mail Queue list

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Anlab#464]
Wrap emails one per line?

![image](https://user-images.githubusercontent.com/469010/35946035-2459fc5a-0c17-11e8-8a88-044bab28fa89.png)

**Comment by srkirkland** [comment]
@jSylvestre i think if you just put spaces between the email addresses that would wrap automatically.  Without spaces it'll never wrap

**Comment by jSylvestre** [comment]
@srkirkland Add the spaces just for display? And replace the ; with a space, or add one?

**Comment by srkirkland** [comment]
@jSylvestre yea my thought would be add a space for display, so when you are joining you'd want to join by "; " instead of just the semicolon
