### ISSUE TITLE
show client phone number as part of confirm/emailed pages

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Anlab#521]

**Comment by jSylvestre** [comment]
![image](https://user-images.githubusercontent.com/469010/37166535-2103f750-22b4-11e8-907c-664711858f7b.png)

**Comment by jSylvestre** [comment]
![image](https://user-images.githubusercontent.com/469010/37166556-390fb47e-22b4-11e8-9cb9-04c162bac424.png)
