### ISSUE TITLE
Add help text for non-UCD IOCs

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Anlab#697]
Create a little thing which shows what format to use for their campus.  We can use it based off this doc:

https://afs.ucdavis.edu/our_services/accounting-e-financial-reporting/documents-folder-not_used_by_navigation/GA_IOC2.xlsx

**Comment by jSylvestre** [comment]
https://afs.ucdavis.edu/our_services/accounting-e-financial-reporting/intercampus-transactions/other-uc-campus-info.html
