### ISSUE TITLE
30 day disposal warning

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Anlab#741]
•	Specific EMAILS from TOPS
o	Generate a 30-day disposal warning
	Clients choose [save] or [dispose] samples
	TOPS knows when the report was sent / finalized.
	When the administrator pushed the button, a list of all clients (with their work request numbers) is generated whose work is past the 30-day grace period.  Administrator would then select all or some of the list to send as a warning.

**Comment by jSylvestre** [comment]
Looking at the data, there are 4 possible values for the LabworksSampleDispositionField:
Blank - Maybe an error
D - Dispose?
R - Return?
S - Save

Have the query list all those that are not D or R ?

**Comment by jSylvestre** [comment]
Look at Peaks bulk edit for multi select

**Comment by srkirkland** [comment]
@jSylvestre this ready to close?
