### ISSUE TITLE
Update IOC email 

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Anlab#744]
•	IOC Billing needs WR#, Work Order #, and often an itemized statement of work.

**Comment by jSylvestre** [comment]
@srkirkland Impossible. That info is not there when the email is generated.

This email needs to be generated *before* they start it.

**Comment by jSylvestre** [comment]
Was thinking agreement

**Comment by jSylvestre** [comment]
This info is All there. Have a link to the review page they would be able to see. Or maybe the lab view.
